### PR TITLE
attempt plantuml latex

### PR DESCRIPTION
**Pull request by alixander**
Screen Shot 2023-03-17 at 2 20 33 PM

`./ci/render.sh latex`

i ran brew upgrade plantuml, but i'm not sure to what version. cli doesn't take any of the standard commands to find out

Screen Shot 2023-03-17 at 2 22 16 PM

### CODE REVIEW

**Comment by chainofreasoning** [comment]
@alixander  I see you are running Mac OSX.  I am using openSuSE Linux.  I was able to replicate your ClassNotFoundException issue on openSuSE Tumbleweed after cloning the site repository.   

 If you install plantuml using a package manager, be aware that it may be missing dependencies on the classpath in order to function with jlatexmath.  openSuSE was missing the needed classpath configuration.  I configured it manually below so as not to depend a package configuration.  I didn't dig into brew to review its packaging.

The key issue is jlatexmath-1.0.7.jar and its dependencies are missing from the classpath.  I ended up needing to use 
-Xbootclasspath/a to get it work with the operating system CLI approach.   I normally use plantuml from a web server or IDE plugin that has the needed *.jar files.

 I downloaded the plantuml.war from here http://sourceforge.net/projects/plantuml/files/plantuml.war/download and tested it with success on Jetty:  https://www.eclipse.org/jetty/download.php.

The plantuml.war file can be unjarred / unzipped to create a directory structure with " WEB-INF/lib/".  This file contains the jar files you will need.

1. I installed plantuml from the openSuSE respository to make the environment similar to yours.
2. I unjarred/unzipped (similar format allows you to use unzip plantuml.war or jar -xvf plantuml.war).
3. I created a java_libs directory in the base text-to-diagram-site repository directory.
4. I copied the libs  I needed (see below) from WEB-INF/lib to the java_libs directory.
5. I set the following environment variable before executing "./ci/render.sh latex" because the linux package installed plantuml looks for it when executing:

`export BASE_FLAGS=-Xbootclasspath/a:java_libs/jlatexmath-1.0.7.jar:java_libs/batik-util-1.14.jar:java_libs/batik-dom-1.14.jar:java_libs/batik-i18n-1.14.jar:java_libs/xml-apis-1.4.01.jar:java_libs/xalan-2.7.2.jar:java_libs/serializer-2.7.2.jar:java_libs/batik-ext-1.14.jar:java_libs/batik-constants-1.14.jar:java_libs/batik-xml-1.14.jar:java_libs/batik-svggen-1.14.jar:java_libs/batik-svg-dom-1.14.jar:java_libs/batik-svgpp-1.14.jar:java_libs/batik-svgrasterizer-1.14.jar:java_libs/batik-svgbrowser-1.14.jar:java_libs/xmlgraphics-commons-2.6.jar:java_libs/batik-awt-util-1.14.jar`

This rendered the correct svg in 11_latext/render directory.

**Comment by alixander** [comment]
thanks so much for sleuthing @chainofreasoning !

Before I dive into it too much, I'm going to cc some plantuml maintainers, fingers crossed they know an easier way >.>

cc @arnaudroques @evantill

**Comment by alixander** [comment]
it looks like the brew package is very up to date, getting love as recently as last week (https://github.com/Homebrew/homebrew-core/pull/125242). which rules out a bad packaging

**Comment by chainofreasoning** [comment]
Other ways include using encoding/decoding.  I've not had the need to use the encode/decode capability of PlantUML.  The main URL is here:

- https://plantuml.com/text-encoding

From the command line you can run from the syntax directory:
`plantuml -encodeurl plantuml.puml`

You will get something like:
`TOvDIyD048Rl-olcQ95W1KzI2r4HUh0z6BmqHQRPIR9aFy9aWz6m_zriAq5GMMO6vdtcORj6sHOP3HJEjCwIzI_-GnCm5HvjfKbqCoAfn5xxZ0QVQbLPCz5GJ8tuD_Na9fNw9BY--JlSeY58MQ7-aS-_W54071rBuWUd7SCZSdElUufhB9gANM_bENhUPPlNDDlijY888VQjHjjuPm-GSBA6VUdOz1eXj_71IgEdOPrhPTx66d9MLUsHsRt34WBa9MCnbXV3PRr8fh48OnrML-UZoN6udGtoXCemoY54yYuwOodVdTJUmJ9yO_yOlm00`

You can then paste that to a root URL (example:  http://www.plantuml.com/plantuml/png/) of a local or remote PlantUML server and receive an image back:

[PlantUML Online URL with appended encoding](http://www.plantuml.com/plantuml/png/TOvDIyD048Rl-olcQ95W1KzI2r4HUh0z6BmqHQRPIR9aFy9aWz6m_zriAq5GMMO6vdtcORj6sHOP3HJEjCwIzI_-GnCm5HvjfKbqCoAfn5xxZ0QVQbLPCz5GJ8tuD_Na9fNw9BY--JlSeY58MQ7-aS-_W54071rBuWUd7SCZSdElUufhB9gANM_bENhUPPlNDDlijY888VQjHjjuPm-GSBA6VUdOz1eXj_71IgEdOPrhPTx66d9MLUsHsRt34WBa9MCnbXV3PRr8fh48OnrML-UZoN6udGtoXCemoY54yYuwOodVdTJUmJ9yO_yOlm00)

From the command line with CURL using the above URL:
`curl http://www.plantuml.com/plantuml/png/TOvDIyD048Rl-olcQ95W1KzI2r4HUh0z6BmqHQRPIR9aFy9aWz6m_zriAq5GMMO6vdtcORj6sHOP3HJEjCwIzI_-GnCm5HvjfKbqCoAfn5xxZ0QVQbLPCz5GJ8tuD_Na9fNw9BY--JlSeY58MQ7-aS-_W54071rBuWUd7SCZSdElUufhB9gANM_bENhUPPlNDDlijY888VQjHjjuPm-GSBA6VUdOz1eXj_71IgEdOPrhPTx66d9MLUsHsRt34WBa9MCnbXV3PRr8fh48OnrML-UZoN6udGtoXCemoY54yYuwOodVdTJUmJ9yO_yOlm00 --output image.png`

I even found a sample Go package: https://pkg.go.dev/github.com/orlade/plantuml-encode/plantuml .

You'll need a configuration with a functional jlatexmath setup in any case though for the rendering side.

**Comment by alixander** [comment]
continues to crash.

**Pull request closed without merging**
